### PR TITLE
Support multiple msg formats for HTTP

### PR DESCRIPTION
**Pull request by Lokesh-K-Haralakatta**
The changes include following:

- Support multiple msg formats for HTTP
- Custom port setting
- Publish command over http
- Some of DM tests disabled as REST API is not stable to avoid test failures in our jenkins build
- Required unit tests for above changes

The changes are tested using the bunch of unit tests.

### CODE REVIEW

**Comment by durera** [comment]
Please undo the changes to domain and self.address before merging this in.

the domain is the top level of the instance of Watson IoT Platform that the client is connecting to, it should not include the "messaging" part ... why was this changed in the first place, was there something not working with the code as-is right now?

Also, why does the change now require the port to tbe passed into the abstractClient rather than have the AbstractClient automatically determine the correct port?

**Comment by Lokesh-K-Haralakatta** [comment]
Hi David,
Actually there are reasons for these changes.

**- Domain to use messaging**: This request has come from the platform team to update in the client libraries to use the revised domain as updated in the latest documentation. You can refer the latest documentation here - https://console.ng.bluemix.net/docs/services/IoT/devices/api.html

**- Option to use custom port:** THis request has come from Honeywell/Wallmart as in most of enterprises, the port 8883 is being blocked. So, we have been asked to add custom port for the user to specify as part of conf file. Java Client library is already updated with this request. So with this change, user can specify 443 as custom port to be used instead of 8883 if it's blocked.

These are the reasons for these changes added to Python Client Library. Can you please review the changes and merge if you don't have any further concerns?

**Comment by durera** [comment]
self.setMessageEncoderModule('text', utf8Codec)
self.setMessageEncoderModule('xml', utf8Codec)
self.setMessageEncoderModule('bin', binaryCodec)


How is the conversion from the data dictionary to utf8/xml/binary working?  Looking at the code you have:

```
def encode(data=None,timestamp=None):
    return data.encode('utf-8')
```

the data parameter for encode is a Python dictionary object,  I do not think Python dict has an encode() method, and a quick test seems to support that ... how does this work?  Likewise with the binaryCodec, I do not believe you can pass a python dictionary to  base64.b64encode().

```
def encode(data=None,timestamp=None):
    return base64.b64encode(data)
```

The XML format is being configured to use the same utf8Codec as "text", so isn't converting the data object either to, or from, XML unless I am missing something so I'm confused as to what that association is doing?

The job of the codec classes is to convert from a plain python dictionary into some format and back again, these new codecs seem to do work if data is a string object, which wouldn't need a codec in the first place.

**Comment by Lokesh-K-Haralakatta** [comment]
Actually the data for the codecs - utf8Codec and binaryCodec is not a Python Dictionary, it's actual data which is going to be transferred as part of payload after encoding. In order to support the http content-type(s) - text/plain and xml, we are using utf8Codec to encode data to charset utf-8 similarly for content-type - application/octetstream, we are using base64 encoding before putting the data into payload. So, with these codecs, we are doing encoding and decoding of the message data.

**Comment by durera** [comment]
You can't just make the codecs work a different way that is incompatible with the design in that manner.  The client always expects to pass a python dictionary to encode and get back a python dictionary from decode, that is the entire point of the codec/mutliple format support in the library.  

If I tried to send an event as XML using that codec it would simply throw an exception in device.publishEvent() .... because you can't call base64.b64encode with a dictionary as the argument.  The library does not expect the user to convert their data into a string and pass that string into publishEvent().

An XML codec would need to use a library like https://pypi.python.org/pypi/dicttoxml to convert between a dictionary object and a XML string.

**Comment by Lokesh-K-Haralakatta** [comment]
For XML, I can incorporate to use dictoxml library. For plain/text and binary data, I don't think we'll have python dictionaries as arguments to client. Is it ok to retain the current codec for text and binary? Will you suggest any changes to be incorporated?

**Comment by durera** [comment]
> For plain/text and binary data, I don't think we'll have python dictionaries as arguments to client
data parameter of sendEvent is *always* a python dictionary.  The whole purpose of the codec system is specifically to convert from the data dictionary to a string that can be sent in the message and back to the dictionary at the other end when it is received.

I have created seperate issues to track the various enhancements under this PR, let's continue discussion in the appropriate issue(s):

https://github.com/ibm-watson-iot/iot-python/issues/46
https://github.com/ibm-watson-iot/iot-python/issues/47
https://github.com/ibm-watson-iot/iot-python/issues/48

I've  changed the HTTP messaging URL (to add the "messaging" part) under the changes in https://github.com/ibm-watson-iot/iot-python/issues/45

**Pull request closed without merging**
